### ISSUE TITLE
Poprawienie dostępów dla cache

### ISSUE THREAD

**Issue by apsg** [itwzhp/cbp#10]
Pipeline ma problemy z dostępami do plików cache:

![image](https://user-images.githubusercontent.com/3952574/223857624-378250d0-ab14-4eb6-bb6c-d47cc7ba8794.png)

Również przy ręcznym odpalaniu czyszczenia cache coś nie gra z dostępami:

![image](https://user-images.githubusercontent.com/3952574/223857779-5b73f3e9-e012-4b7f-b1bb-99a017d0ba32.png)

**Comment by karol-gro** [comment]
deployment pracuje z usera build, a php pracuje chyba w zhp, ale nie jestem pewien. Pododwałem tych userów do swoich grup nawzajem i ręcznie puściłem `chmod -R g+w .`.

Pytanie, jak to naprostować, bo jest rzeczywiście bałagan z tymi grupami

**Comment by apsg** [comment]
Jednym rozwiązaniem jest nie czyścić całego katalogu aplikacji. 
Rsync ma opcję exclude - można  go zmodyfikować tak, by olał katalogi:
-  `storage/framework` 
- `storage/logs`
- `storage/debugbar`

**Comment by apsg** [comment]
Wywaliłem tego `rm` i dodałem w rsyncu exclude - to działa. Z poziomu ssh jednak dalej nie mogę ani edytować plików, ani wyczyścić cache

**Comment by Szymen** [comment]
https://github.com/itwzhp/cbp/pull/11 tu jest PR
