### ISSUE TITLE
Brak pliku licencji

### ISSUE THREAD

**Issue by Maniues** [itwzhp/cbp#12]
Do tego projektu nie ma przypisanej licencji.
Problem występuje też w innych repozytoriach w organizacji.
Brak pliku licencji jest kłopotliwy dla użytkowników tego kodu, ale również dla przyjmowania ewentualnych pull requestów.
Problem ten nie występuje jedynie w repozytorium zhp-pl, gdzie ustawiona jest licencja MIT.
Dla pozostałych repozytoriów sugeruję wybranie również licencji MIT, gdyż zapewni to jednolitość.

**Comment by karol-gro** [comment]
Dobre spostrzeżenie. @apsg , czy umowa specyfikuje konkretną licencję? Jeśli jest pełne przeniesienie praw to pewnie ZHP wyda na MIT
Nie wiem tylko, czy licencję należałoby wyspecyfikować teraz czy po oddaniu

**Comment by karol-gro** [comment]
Wydaje mi się, że (o ile umowa nie stanowi inaczej) publikacja na konkretnej licencji może się odbyć dopiero po przekazaniu praw autorskich, bo wg standardowej umowy o dzieło w obecnym momencie ZHP nie ma praw licencyjnych, a z kolei autor jest zobowiązany do przekazania pełni praw wyłącznych, więc nie może też udzielać innych licencji. Więc o ile nie było to uwzględnione w umowie to trzeba by podpisać aneks... albo poczekać na oddanie projektu i wtedy ZHP udostępni pewnie na MIT. Do tego czasu z przyczyn formalnych mimo udostępnienia kodu nie jest udzielana licencja na niego

Jeśli chcesz tego kodu użyć to myślę, że i tak warto poczekać aż będzie przetestowany i produkcyjny. A jak chcesz mimo wszystko szybciej to skontaktuj się z @AnnaPospieszna i @apsg 

Za to jeśli chcesz zrobić PR to już temat z @apsg bo do czasu przekazania dzieła posiada on pełnię praw autorskich.

**Comment by karol-gro** [comment]
Tak, to jest cbp2.0. Możesz już go zobaczyć na https://cbp-dev.zhp.pl

Dodałem licencję MIT w ZHPAccounts. Infrastruktura będzie pewnie uprywatniona, SIM jest w podobnym stanie co CBP, tj czeka na odbiór, a Bikejamboree nie należy do nas (tylko do Fundacji Jamboree). Możesz ew. wystawić issue w tym ostatnim, ale nie wiem czy ich admin tam zagląda

**Comment by karol-gro** [comment]
Myślę, że będzie na MIT lub czymś podobnym, o ile nie zapomnę dodać pliku ;) A cbp w wersji 1.0 to po prostu odpowiednio ustawiony Wordpress, nie wiem czy i ile naszego kodu tam w ogóle jest (ale swoją drogą też autorem jest @apsg )

**Comment by karol-gro** [comment]
HarcApp nie jest aplikacją ZHP tylko prywatnie rozwijaną przez Daniela, więc musiałbyś z nim to negocjować

**Comment by karol-gro** [comment]
Dobre pytanie, @apsg - jak wygląda kwestia przekazania praw autorskich?

**Comment by karol-gro** [comment]
Dobre pytanie, nie mam pojęcia, odsyłam do @apsg

**Comment by karol-gro** [comment]
ja nie pracuję, jestem wolontariuszem ;)
