### ISSUE TITLE
strona główna - "proponowane tematy" na głównej stronie

### ISSUE THREAD

**Issue by AnnaPospieszna** [itwzhp/cbp#28]
Nazwę "proponowane tematy" zamieniamy na -> "Znajdź materiał"

Czy w tych białych polach da się zrobić ikonki/obrazki zamiast szarych pól? w sensie obrazki? Jak tak to tu wrzucimy? Czy mają być okrągłe czy w kwadracie je wrzucać?

**Comment by apsg** [comment]
Wrzućcie ikonki najlepiej kółka
