### ISSUE TITLE
usunięcie daty

### ISSUE THREAD

**Issue by AnnaPospieszna** [itwzhp/cbp#35]
![obraz](https://github.com/itwzhp/cbp/assets/84130472/4cb8ed18-aa73-4b36-9f77-7d353c6fc6cb)

poprosimy jednak o usunięcie tutaj w wyświetlaniu materiałów daty  : )

**Comment by PUMCZACZ** [comment]
@apsg https://github.com/itwzhp/cbp/pull/38
