### ISSUE TITLE
Slider

### ISSUE THREAD

**Issue by AnnaPospieszna** [itwzhp/cbp#37]
Poprosimy na slider z tymi zdjeciami

![slider1](https://github.com/itwzhp/cbp/assets/84130472/8273c6d4-b707-4e11-a923-668480690b4c)
![slider2](https://github.com/itwzhp/cbp/assets/84130472/13f2bd12-aa07-4ada-87b9-eb14941c259f)
![slider4](https://github.com/itwzhp/cbp/assets/84130472/ff2d4bd5-f710-4a3c-985c-3624075e15eb)
![slider3](https://github.com/itwzhp/cbp/assets/84130472/310dfcab-ee5b-41d2-bf32-65391b455382)

**Comment by apsg** [comment]
Do czego każdy z tych slajdów ma linkować?
