### ISSUE TITLE
Pobieranie z Microsoftu zdjęcia z profilu

### ISSUE THREAD

**Issue by AnnaPospieszna** [itwzhp/cbp#52]
Czy możliwe jest podczas logowania użytkownika przez oath na konto zhp wyciągać jego profilówkę? Logowanie odbywa się poprzez wtyczkę socialite do Laravela?

**Comment by AnnaPospieszna** [comment]
Trzeba dodać w aad uprawnienie do user.readall -> cyz to Ci @apsg  pomoże?

**Comment by karol-gro** [comment]
Nie znam laravela, ale generalnie (wg tej dokumentacji: https://learn.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-1.0&tabs=http ) wystarczy uprawnienie user.read, aby odczytać podczas logowania się avatar użytkownika. Jeśli jednak ktoś zmieni awatar to będzie musiał wejść na CBP, żeby się na nim odświeżył. Gdybyśmy chcieli mieć np. automatycznie odświeżane awatary co noc to rzeczywiście user.readall będzie potrzebne
