### ISSUE TITLE
Kafelki na 1 stronie

### ISSUE THREAD

**Issue by AnnaPospieszna** [itwzhp/cbp#60]
Pod kafelkiem czasopisma na pierwszej stronie pojawia się filtr ZUCHY, a nie czasopisma.

oraz

Poprosimy o kolejność kafelków
- materiały zuchowe 
- materiały harcerskie 
- materiąły starszoharcerskie 
- materiały wędrownicze 
- propozycje programowe (zmiana kolejności z konspektem kształceniowym)
- gra programowa 
- gra kształceniowa
- konspekt kształceniowy (zmiana kolejności z propozycją programową)
- poradniki
- czasopisma
- artykuły
- recenzje (dodać, bo jest to typ materiału) - jest znaczek jak coś na mailu, ale podbiję jak coś

**Comment by apsg** [comment]
@AnnaPospieszna trzeba dodać typ/tag "Czasopisma" - brakuje go w bazie a ja nie mam dostępu bo nie mogę się zlaogować
